/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly Full 19.0.0.Final (WildFly Core 11.0.0.Final) - 2.0.30.Final
 * Generated at: 2020-05-30 17:40:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entity.Client;
import entity.Restaurant;
import entity.Category;
import java.util.List;

public final class restaurant_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("entity.Category");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("entity.Client");
    _jspx_imports_classes.add("entity.Restaurant");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" />\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-2.2.4.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Food Menu - Restaurante</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"sortcut icon\" href=\"../assets/favicon.ico\"\r\n");
      out.write("\ttype=\"image/x-icon\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		Client clientLogged = (Client) session.getAttribute("clientLogged");
	Restaurant restaurant = (Restaurant) session.getAttribute("restaurant");
	@SuppressWarnings("unchecked")
	List<Category> categories = (List<Category>) session.getAttribute("categories");
	if (clientLogged == null) {
		response.sendRedirect("./login.jsp");
	} else {
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-lg navbar-danger bg-danger\">\r\n");
      out.write("\t\t<a class=\"navbar-brand text-light font-weight-bold\"\r\n");
      out.write("\t\t\thref=\"../ClientServlet?pageURL=main.jsp?&clientID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientLogged.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Food\r\n");
      out.write("\t\t\tMenu</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\tdata-target=\"#navbarNavDropdown\" aria-controls=\"navbarNavDropdown\"\r\n");
      out.write("\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarNavDropdown\">\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link text-light font-weight-bold\"\r\n");
      out.write("\t\t\t\t\thref=\"../ClientServlet?pageURL=profile.jsp?&clientID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientLogged.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Perfil\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link text-light font-weight-bold\"\r\n");
      out.write("\t\t\t\t\thref=\"../ClientServlet?pageURL=restaurant_edit.jsp?&clientID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientLogged.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Restaurante</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown text-light\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle text-light font-weight-bold\"\r\n");
      out.write("\t\t\t\t\thref=\"#\" id=\"navbarDropdownMenuLink\" role=\"button\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\tCardápio </a>\r\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu bg-danger\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"navbarDropdownMenuLink\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item text-light font-weight-bold\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"../ClientServlet?pageURL=categories.jsp?&clientID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientLogged.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Categorias</a>\r\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item text-light font-weight-bold\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"../ClientServlet?pageURL=products.jsp?&clientID=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientLogged.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Produtos</a>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link text-light font-weight-bold\"\r\n");
      out.write("\t\t\t\t\thref=\"../ClientServlet?pageURL=login.jsp\">Sair</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"card card-group bg-danger\">\r\n");
      out.write("\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t<h2 class=\"card-title font-weight-bold\">Sobre o restaurante:</h2>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t<form class=\"needs-validation\" novalidate method=\"get\"\r\n");
      out.write("\t\t\t\t\taction=\"../RestaurantServlet\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"restaurantID\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${restaurant.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"pageURL\" value=\"restaurant_edit.jsp\" /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"clientID\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${clientLogged.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=hidden name=_method value=PUT />\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputCnpj\">CNPJ</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputCnpj\" name=\"cnpj\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Qual o CPNJ do restaurante?\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getCnpj());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o cnpj do\r\n");
      out.write("\t\t\t\t\t\t\t\trestaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputNameRestaurant\">Nome do Restaurante</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"inputNameRestaurant\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"name\" placeholder=\"Qual o nome do restaurante?\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(restaurant.getName());
      out.write("\" min=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\tmax=\"60\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o nome do\r\n");
      out.write("\t\t\t\t\t\t\t\trestaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputDescription\">Descrição (Opcional)</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"inputDescription\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"description\" value=\"");
      out.print(restaurant.getDescription());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Faça uma descrição do seu restaurante\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputPhone\">Telefone</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputPhone\" name=\"phone\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Qual é o telefone do restaurante?\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(restaurant.getPhone());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o telefone\r\n");
      out.write("\t\t\t\t\t\t\t\tdo restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputCep\">CEP</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputCep\" name=\"cep\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"CEP do restaurante\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getCep());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o CEP do\r\n");
      out.write("\t\t\t\t\t\t\t\trestaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputCity\">Cidade</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputCity\" name=\"city\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Cidade do restaurante\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getCity());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe a cidade\r\n");
      out.write("\t\t\t\t\t\t\t\tdo restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputState\">Estado</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputState\" name=\"state\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"UF do restaurante\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getState());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o estado\r\n");
      out.write("\t\t\t\t\t\t\t\tdo restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputDistrict\">Bairro</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputDistrict\" name=\"district\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Bairro do restaurante\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getDistrict());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o bairro\r\n");
      out.write("\t\t\t\t\t\t\t\tdo restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputAddress\">Endereço</label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputAdress\" name=\"address\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Qual o endereço do restaurante?\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(restaurant.getAddress());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o endereço\r\n");
      out.write("\t\t\t\t\t\t\t\tdo restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputNumber\">Número</label> <input type=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\" id=\"inputNumber\" name=\"number\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Número do endereço\" required=\"required\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getNumber());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o número\r\n");
      out.write("\t\t\t\t\t\t\t\tdo endereço do restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputAddtion\">Complemento (Opcional)</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"inputAddtion\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"addition\" value=\"");
      out.print(restaurant.getAddition());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Complemento do endereço\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputTimeBegin\">Horário de Abertura</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"inputTimeBegin\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"time_open\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Qual horário seu estabelecimento abre?\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(restaurant.getTime_open());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o horário\r\n");
      out.write("\t\t\t\t\t\t\t\tde abertura do restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputTimeEnd\">Horário de Encerramento</label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" class=\"form-control\" id=\"inputTimeEnd\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"time_close\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Qual horário seu estabelecimento fecha?\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(restaurant.getTime_close());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe o horário\r\n");
      out.write("\t\t\t\t\t\t\t\tde encerramento do restaurante.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputDays\">Quais dias o restaurante funciona?</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isMonday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"monday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"monday\" checked=\"checked\" onclick=\"check('monday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"monday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"monday\" onclick=\"check('monday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"monday\">Segunda-Feira</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isTuesday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"tuesday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tuesday\" checked=\"checked\" onclick=\"check('tuesday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"tuesday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"tuesday\" onclick=\"check('tuesday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"tuesday\">Terça-Feira</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isWednesday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"wednesday\" name=\"wednesday\" checked=\"checked\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"check('wednesday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"wednesday\" name=\"wednesday\" onclick=\"check('wednesday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"wednesday\">Quarta-Feira</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isThursday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"thursday\" name=\"thursday\" checked=\"checked\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"check('thursday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"thursday\" name=\"thursday\" onclick=\"check('thursday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"thursday\">Quinta-Feira</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isFriday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"friday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"friday\" checked=\"checked\" onclick=\"check('friday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"friday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"friday\" onclick=\"check('friday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"friday\">Sexta-Feira</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isSaturday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"saturday\" name=\"saturday\" checked=\"checked\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"check('saturday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"saturday\" name=\"saturday\" onclick=\"check('saturday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"saturday\">Sabádo</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-checkbox custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.isSunday_open()) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"sunday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"sunday\" checked=\"checked\" onclick=\"check('sunday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"checkbox\" class=\"custom-control-input\" id=\"sunday\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"sunday\" onclick=\"check('sunday')\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<label class=\"custom-control-label\" for=\"sunday\">Domingo</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputEspeciality\">Qual a categoria principal\r\n");
      out.write("\t\t\t\t\t\t\t\tdo restaurante?</label> <select class=\"custom-select\"\r\n");
      out.write("\t\t\t\t\t\t\t\trequired=\"required\" name=\"category\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									if (restaurant.getCategory() != null) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected=\"selected\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(restaurant.getCategory().getId());
      out.write('"');
      out.write('>');
      out.print(restaurant.getCategory().getName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									} else {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option selected=\"selected\"></option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								if (categories != null) {
									for (Category categoryProduct : categories) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(categoryProduct.getId());
      out.write('"');
      out.write('>');
      out.print(categoryProduct.getName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

									}
								}
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"invalid-feedback\">Por favor, informe a\r\n");
      out.write("\t\t\t\t\t\t\t\tcategoria principal do restaurante. Caso não encontre uma\r\n");
      out.write("\t\t\t\t\t\t\t\tcategoria apropriada, vá em: Cardápio => Categorias. Para criar\r\n");
      out.write("\t\t\t\t\t\t\t\tuma nova categoria.</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body form-group col-md-15 font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputDelivery\">O restaurante possui serviço\r\n");
      out.write("\t\t\t\t\t\t\t\tde entrega?</label> <br />\r\n");
      out.write("\t\t\t\t\t\t\t");

								if (restaurant.isDelivery()) {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"customRadioDeliveryYes\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"radio('customRadioDeliveryYes', 'customRadioDeliveryNo')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"delivery\" class=\"custom-control-input\" checked=\"checked\" /><label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"custom-control-label\" for=\"customRadioDeliveryYes\">Sim</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"customRadioDeliveryNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"radio('customRadioDeliveryYes', 'customRadioDeliveryNo')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"delivery\" class=\"custom-control-input\" /><label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"custom-control-label\" for=\"customRadioDeliveryNo\">Não</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"customRadioDeliveryYes\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"radio('customRadioDeliveryYes', 'customRadioDeliveryNo')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"delivery\" class=\"custom-control-input\" /><label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"custom-control-label\" for=\"customRadioDeliveryYes\">Sim</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"custom-control custom-radio custom-control-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"radio\" id=\"customRadioDeliveryNo\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tonclick=\"radio('customRadioDeliveryYes', 'customRadioDeliveryNo')\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"delivery\" class=\"custom-control-input\" checked=\"checked\" /><label\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"custom-control-label\" for=\"customRadioDeliveryNo\">Não</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-danger btn-lg btn-block font-weight-bold\">\r\n");
      out.write("\t\t\t\t\t\tSalvar Mudanças</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.0/jquery.mask.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"https://github.com/igorescobar/jQuery-Mask-Plugin/blob/master/dist/jquery.mask.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#inputCnpj\").mask(\"99.999.999/9999-99\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#inputCep\").mask(\"99.999-999\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#inputPhone\").mask(\"(00) 0000-00009\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#inputTimeBegin\").mask(\"00:00\");\r\n");
      out.write("\t\t$(\"#inputTimeEnd\").mask(\"00:00\");\r\n");
      out.write("\r\n");
      out.write("\t\tfunction check(checkID) {\r\n");
      out.write("\t\t\tvar checkBox = document.getElementById(checkID);\r\n");
      out.write("\t\t\tif (checkBox.checked == true) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(checkID).value = \"on\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.getElementById(checkID).value = \"off\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction radio(radioIDY, radioIDN) {\r\n");
      out.write("\t\t\tvar radioY = document.getElementById(radioIDY);\r\n");
      out.write("\t\t\tvar radioN = document.getElementById(radioIDN);\r\n");
      out.write("\t\t\tif (radioY.checked == true) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(radioIDY).value = \"onYes\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(radioIDN).value = \"offNo\";\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tdocument.getElementById(radioIDY).value = \"offYes\";\r\n");
      out.write("\t\t\t\tdocument.getElementById(radioIDN).value = \"onNo\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// Exemplo de JavaScript inicial para desativar envios de formulário, se houver campos inválidos.\r\n");
      out.write("\t\t(function() {\r\n");
      out.write("\t\t\t'use strict';\r\n");
      out.write("\t\t\twindow.addEventListener('load',\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t// Pega todos os formulários que nós queremos aplicar estilos de validação Bootstrap personalizados.\r\n");
      out.write("\t\t\t\t\t\tvar forms = document\r\n");
      out.write("\t\t\t\t\t\t\t\t.getElementsByClassName('needs-validation');\r\n");
      out.write("\t\t\t\t\t\t// Faz um loop neles e evita o envio\r\n");
      out.write("\t\t\t\t\t\tvar validation = Array.prototype.filter.call(forms,\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction(form) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tform.addEventListener('submit', function(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tevent) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif (form.checkValidity() === false) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tevent.stopPropagation();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tform.classList.add('was-validated');\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}, false);\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}, false);\r\n");
      out.write("\t\t})();\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
